Test changes, the current bug is:
Caused by: java.lang.NoSuchMethodError: org.ujorm.extensions.Property.newInstance(Ljava/lang/String;Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/Integer;Z)Lorg/ujorm/extensions/Property;
	at org.ujorm.core.KeyFactory.createKey(KeyFactory.java:323)
	at org.ujorm.core.KeyFactory.newKey(KeyFactory.java:294)
	at com.inspectime.commons.bo.User_TEST.<clinit>(User_TEST.java:36)